directories:
  output: release
  buildResources: build
appId: com.zemelee.wechat_top
productName: WeChat Frontend
copyright: Copyright © 2024 zemelee
files:
  - filter:
      - dist/**/*
      - main.cjs
win:
  target: nsis
  icon: public/wx.png
mac:
  target: dmg
  icon: public/wx.png
linux:
  target: AppImage
  icon: public/wx.png
electronVersion: 32.2.7
